# VPS-RPC 配置文件

[server]
# 服务器配置
port = 4242

[quic]
# QUIC配置
max_idle_timeout = "30s"
handshake_idle_timeout = "5s"
max_incoming_streams = 100
max_incoming_uni_streams = 100

[crawler]
# 爬虫配置
default_timeout = "30s"
max_concurrent_requests = 10

[crawler.default_headers]
Accept = "*/*"
Accept-Encoding = "gzip, deflate, br, zstd"
Accept-Language = "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2"
TE = "trailers"

[tls]
# TLS配置（指纹类型不再由配置指定，系统将随机选择受支持的指纹）

[logging]
# 日志配置
level = "info"
format = "json"
# 日志缓冲区大小（最多保存的日志条目数量）
buffer_size = 1000

[client]
# 客户端配置
# 客户端连接的默认超时时间
default_timeout = "10s"
# 连接池的默认最大连接数
default_pool_size = 10

[client.retry]
# 重试配置
# 最大重试次数
max_retries = 3
# 初始延迟时间
initial_delay = "100ms"
# 最大延迟时间
max_delay = "5s"
# 延迟乘数（指数退避）
multiplier = 2.0

[admin]
# 管理服务配置
# 服务器版本号
version = "1.0.206"
# 日志缓冲区大小（最多保存的日志条目数量）
log_buffer_size = 1000
# 默认最大日志行数
default_max_log_lines = 100
# 最大日志行数限制
max_log_lines = 1000

[dns]
# DNS 池配置
enabled = true
db_path = "./dns_pool.bolt"
refresh_interval = "24h"
blacklist_duration = "6h"  # 兼容字段：当前实现为“无过期黑名单”，该字段不生效

[peer]
# 种子节点（公网可达，域名或 IP:端口）。1-3 个即可
# seeds = [
#   "node1.example.com:4242",
#   "203.0.113.10:4242"
# ]
