// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: rpc/admin_service.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 状态请求
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_rpc_admin_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_admin_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_rpc_admin_service_proto_rawDescGZIP(), []int{0}
}

// 状态响应
type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 服务器运行状态
	Running bool `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	// 启动时间（Unix时间戳）
	StartTime int64 `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// 运行时长（秒）
	UptimeSeconds int64 `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	// 版本信息
	Version string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	// 监听地址
	ListenAddress string `protobuf:"bytes,5,opt,name=listen_address,json=listenAddress,proto3" json:"listen_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_rpc_admin_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_admin_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_rpc_admin_service_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *StatusResponse) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *StatusResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *StatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StatusResponse) GetListenAddress() string {
	if x != nil {
		return x.ListenAddress
	}
	return ""
}

// 统计请求
type StatsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否重置统计信息
	Reset_        bool `protobuf:"varint,1,opt,name=reset,proto3" json:"reset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_rpc_admin_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_admin_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_admin_service_proto_rawDescGZIP(), []int{2}
}

func (x *StatsRequest) GetReset_() bool {
	if x != nil {
		return x.Reset_
	}
	return false
}

// 统计响应
type StatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 总请求数
	TotalRequests int64 `protobuf:"varint,1,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	// 成功请求数
	SuccessRequests int64 `protobuf:"varint,2,opt,name=success_requests,json=successRequests,proto3" json:"success_requests,omitempty"`
	// 失败请求数
	ErrorRequests int64 `protobuf:"varint,3,opt,name=error_requests,json=errorRequests,proto3" json:"error_requests,omitempty"`
	// 平均延迟（毫秒）
	AverageLatencyMs int64 `protobuf:"varint,4,opt,name=average_latency_ms,json=averageLatencyMs,proto3" json:"average_latency_ms,omitempty"`
	// 最小延迟（毫秒）
	MinLatencyMs int64 `protobuf:"varint,5,opt,name=min_latency_ms,json=minLatencyMs,proto3" json:"min_latency_ms,omitempty"`
	// 最大延迟（毫秒）
	MaxLatencyMs int64 `protobuf:"varint,6,opt,name=max_latency_ms,json=maxLatencyMs,proto3" json:"max_latency_ms,omitempty"`
	// 当前并发连接数
	CurrentConnections int64 `protobuf:"varint,7,opt,name=current_connections,json=currentConnections,proto3" json:"current_connections,omitempty"`
	// 错误统计（错误码 -> 次数）
	ErrorStats map[string]int64 `protobuf:"bytes,8,rep,name=error_stats,json=errorStats,proto3" json:"error_stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// 统计开始时间（Unix时间戳）
	StatsStartTime int64 `protobuf:"varint,9,opt,name=stats_start_time,json=statsStartTime,proto3" json:"stats_start_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_rpc_admin_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_admin_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_admin_service_proto_rawDescGZIP(), []int{3}
}

func (x *StatsResponse) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *StatsResponse) GetSuccessRequests() int64 {
	if x != nil {
		return x.SuccessRequests
	}
	return 0
}

func (x *StatsResponse) GetErrorRequests() int64 {
	if x != nil {
		return x.ErrorRequests
	}
	return 0
}

func (x *StatsResponse) GetAverageLatencyMs() int64 {
	if x != nil {
		return x.AverageLatencyMs
	}
	return 0
}

func (x *StatsResponse) GetMinLatencyMs() int64 {
	if x != nil {
		return x.MinLatencyMs
	}
	return 0
}

func (x *StatsResponse) GetMaxLatencyMs() int64 {
	if x != nil {
		return x.MaxLatencyMs
	}
	return 0
}

func (x *StatsResponse) GetCurrentConnections() int64 {
	if x != nil {
		return x.CurrentConnections
	}
	return 0
}

func (x *StatsResponse) GetErrorStats() map[string]int64 {
	if x != nil {
		return x.ErrorStats
	}
	return nil
}

func (x *StatsResponse) GetStatsStartTime() int64 {
	if x != nil {
		return x.StatsStartTime
	}
	return 0
}

// 更新配置请求
type UpdateConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 配置项名称
	ConfigKey string `protobuf:"bytes,1,opt,name=config_key,json=configKey,proto3" json:"config_key,omitempty"`
	// 配置项值（JSON格式）
	ConfigValue   string `protobuf:"bytes,2,opt,name=config_value,json=configValue,proto3" json:"config_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigRequest) Reset() {
	*x = UpdateConfigRequest{}
	mi := &file_rpc_admin_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigRequest) ProtoMessage() {}

func (x *UpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_admin_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) {
	return file_rpc_admin_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateConfigRequest) GetConfigKey() string {
	if x != nil {
		return x.ConfigKey
	}
	return ""
}

func (x *UpdateConfigRequest) GetConfigValue() string {
	if x != nil {
		return x.ConfigValue
	}
	return ""
}

// 更新配置响应
type UpdateConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否成功
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// 错误信息
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// 更新后的配置（JSON格式）
	UpdatedConfig string `protobuf:"bytes,3,opt,name=updated_config,json=updatedConfig,proto3" json:"updated_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigResponse) Reset() {
	*x = UpdateConfigResponse{}
	mi := &file_rpc_admin_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigResponse) ProtoMessage() {}

func (x *UpdateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_admin_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateConfigResponse) Descriptor() ([]byte, []int) {
	return file_rpc_admin_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateConfigResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UpdateConfigResponse) GetUpdatedConfig() string {
	if x != nil {
		return x.UpdatedConfig
	}
	return ""
}

// 日志请求
type LogsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 日志级别（空表示所有级别）
	Level string `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	// 最大行数
	MaxLines int32 `protobuf:"varint,2,opt,name=max_lines,json=maxLines,proto3" json:"max_lines,omitempty"`
	// 是否实时（流式返回）
	Follow        bool `protobuf:"varint,3,opt,name=follow,proto3" json:"follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsRequest) Reset() {
	*x = LogsRequest{}
	mi := &file_rpc_admin_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsRequest) ProtoMessage() {}

func (x *LogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_admin_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsRequest.ProtoReflect.Descriptor instead.
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_admin_service_proto_rawDescGZIP(), []int{6}
}

func (x *LogsRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogsRequest) GetMaxLines() int32 {
	if x != nil {
		return x.MaxLines
	}
	return 0
}

func (x *LogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

// 日志响应
type LogsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 日志条目
	Entries []*LogEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	// 是否还有更多日志
	HasMore       bool `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsResponse) Reset() {
	*x = LogsResponse{}
	mi := &file_rpc_admin_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsResponse) ProtoMessage() {}

func (x *LogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_admin_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsResponse.ProtoReflect.Descriptor instead.
func (*LogsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_admin_service_proto_rawDescGZIP(), []int{7}
}

func (x *LogsResponse) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *LogsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// 日志条目
type LogEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 时间戳（Unix时间戳）
	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// 日志级别
	Level string `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	// 日志消息
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// 附加字段（JSON格式）
	Fields        string `protobuf:"bytes,4,opt,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_rpc_admin_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_admin_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_rpc_admin_service_proto_rawDescGZIP(), []int{8}
}

func (x *LogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetFields() string {
	if x != nil {
		return x.Fields
	}
	return ""
}

// 健康检查请求
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_rpc_admin_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_admin_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_rpc_admin_service_proto_rawDescGZIP(), []int{9}
}

// 健康检查响应
type HealthCheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 健康状态
	Healthy bool `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	// 状态消息
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// 检查时间（Unix时间戳）
	CheckTime     int64 `protobuf:"varint,3,opt,name=check_time,json=checkTime,proto3" json:"check_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_rpc_admin_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_admin_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_rpc_admin_service_proto_rawDescGZIP(), []int{10}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheckResponse) GetCheckTime() int64 {
	if x != nil {
		return x.CheckTime
	}
	return 0
}

// 连接信息请求
type ConnectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionsRequest) Reset() {
	*x = ConnectionsRequest{}
	mi := &file_rpc_admin_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionsRequest) ProtoMessage() {}

func (x *ConnectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_admin_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionsRequest.ProtoReflect.Descriptor instead.
func (*ConnectionsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_admin_service_proto_rawDescGZIP(), []int{11}
}

// 连接信息响应
type ConnectionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 连接信息列表
	Connections []*ConnectionInfo `protobuf:"bytes,1,rep,name=connections,proto3" json:"connections,omitempty"`
	// 总连接数
	TotalConnections int32 `protobuf:"varint,2,opt,name=total_connections,json=totalConnections,proto3" json:"total_connections,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConnectionsResponse) Reset() {
	*x = ConnectionsResponse{}
	mi := &file_rpc_admin_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionsResponse) ProtoMessage() {}

func (x *ConnectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_admin_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionsResponse.ProtoReflect.Descriptor instead.
func (*ConnectionsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_admin_service_proto_rawDescGZIP(), []int{12}
}

func (x *ConnectionsResponse) GetConnections() []*ConnectionInfo {
	if x != nil {
		return x.Connections
	}
	return nil
}

func (x *ConnectionsResponse) GetTotalConnections() int32 {
	if x != nil {
		return x.TotalConnections
	}
	return 0
}

// 连接信息
type ConnectionInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 客户端地址
	ClientAddress string `protobuf:"bytes,1,opt,name=client_address,json=clientAddress,proto3" json:"client_address,omitempty"`
	// 连接时间（Unix时间戳）
	ConnectTime int64 `protobuf:"varint,2,opt,name=connect_time,json=connectTime,proto3" json:"connect_time,omitempty"`
	// 最后活动时间（Unix时间戳）
	LastActivityTime int64 `protobuf:"varint,3,opt,name=last_activity_time,json=lastActivityTime,proto3" json:"last_activity_time,omitempty"`
	// 状态
	State         string `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionInfo) Reset() {
	*x = ConnectionInfo{}
	mi := &file_rpc_admin_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionInfo) ProtoMessage() {}

func (x *ConnectionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_admin_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionInfo.ProtoReflect.Descriptor instead.
func (*ConnectionInfo) Descriptor() ([]byte, []int) {
	return file_rpc_admin_service_proto_rawDescGZIP(), []int{13}
}

func (x *ConnectionInfo) GetClientAddress() string {
	if x != nil {
		return x.ClientAddress
	}
	return ""
}

func (x *ConnectionInfo) GetConnectTime() int64 {
	if x != nil {
		return x.ConnectTime
	}
	return 0
}

func (x *ConnectionInfo) GetLastActivityTime() int64 {
	if x != nil {
		return x.LastActivityTime
	}
	return 0
}

func (x *ConnectionInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

var File_rpc_admin_service_proto protoreflect.FileDescriptor

const file_rpc_admin_service_proto_rawDesc = "" +
	"\n" +
	"\x17rpc/admin_service.proto\x12\x03rpc\"\x0f\n" +
	"\rStatusRequest\"\xb1\x01\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x03R\tstartTime\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12%\n" +
	"\x0elisten_address\x18\x05 \x01(\tR\rlistenAddress\"$\n" +
	"\fStatsRequest\x12\x14\n" +
	"\x05reset\x18\x01 \x01(\bR\x05reset\"\xe1\x03\n" +
	"\rStatsResponse\x12%\n" +
	"\x0etotal_requests\x18\x01 \x01(\x03R\rtotalRequests\x12)\n" +
	"\x10success_requests\x18\x02 \x01(\x03R\x0fsuccessRequests\x12%\n" +
	"\x0eerror_requests\x18\x03 \x01(\x03R\rerrorRequests\x12,\n" +
	"\x12average_latency_ms\x18\x04 \x01(\x03R\x10averageLatencyMs\x12$\n" +
	"\x0emin_latency_ms\x18\x05 \x01(\x03R\fminLatencyMs\x12$\n" +
	"\x0emax_latency_ms\x18\x06 \x01(\x03R\fmaxLatencyMs\x12/\n" +
	"\x13current_connections\x18\a \x01(\x03R\x12currentConnections\x12C\n" +
	"\verror_stats\x18\b \x03(\v2\".rpc.StatsResponse.ErrorStatsEntryR\n" +
	"errorStats\x12(\n" +
	"\x10stats_start_time\x18\t \x01(\x03R\x0estatsStartTime\x1a=\n" +
	"\x0fErrorStatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"W\n" +
	"\x13UpdateConfigRequest\x12\x1d\n" +
	"\n" +
	"config_key\x18\x01 \x01(\tR\tconfigKey\x12!\n" +
	"\fconfig_value\x18\x02 \x01(\tR\vconfigValue\"m\n" +
	"\x14UpdateConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12%\n" +
	"\x0eupdated_config\x18\x03 \x01(\tR\rupdatedConfig\"X\n" +
	"\vLogsRequest\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x1b\n" +
	"\tmax_lines\x18\x02 \x01(\x05R\bmaxLines\x12\x16\n" +
	"\x06follow\x18\x03 \x01(\bR\x06follow\"R\n" +
	"\fLogsResponse\x12'\n" +
	"\aentries\x18\x01 \x03(\v2\r.rpc.LogEntryR\aentries\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"p\n" +
	"\bLogEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x16\n" +
	"\x06fields\x18\x04 \x01(\tR\x06fields\"\x14\n" +
	"\x12HealthCheckRequest\"h\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"check_time\x18\x03 \x01(\x03R\tcheckTime\"\x14\n" +
	"\x12ConnectionsRequest\"y\n" +
	"\x13ConnectionsResponse\x125\n" +
	"\vconnections\x18\x01 \x03(\v2\x13.rpc.ConnectionInfoR\vconnections\x12+\n" +
	"\x11total_connections\x18\x02 \x01(\x05R\x10totalConnections\"\x9e\x01\n" +
	"\x0eConnectionInfo\x12%\n" +
	"\x0eclient_address\x18\x01 \x01(\tR\rclientAddress\x12!\n" +
	"\fconnect_time\x18\x02 \x01(\x03R\vconnectTime\x12,\n" +
	"\x12last_activity_time\x18\x03 \x01(\x03R\x10lastActivityTime\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state2\xf3\x02\n" +
	"\fAdminService\x124\n" +
	"\tGetStatus\x12\x12.rpc.StatusRequest\x1a\x13.rpc.StatusResponse\x121\n" +
	"\bGetStats\x12\x11.rpc.StatsRequest\x1a\x12.rpc.StatsResponse\x12C\n" +
	"\fUpdateConfig\x12\x18.rpc.UpdateConfigRequest\x1a\x19.rpc.UpdateConfigResponse\x12.\n" +
	"\aGetLogs\x12\x10.rpc.LogsRequest\x1a\x11.rpc.LogsResponse\x12@\n" +
	"\vHealthCheck\x12\x17.rpc.HealthCheckRequest\x1a\x18.rpc.HealthCheckResponse\x12C\n" +
	"\x0eGetConnections\x12\x17.rpc.ConnectionsRequest\x1a\x18.rpc.ConnectionsResponseB\aZ\x05./rpcb\x06proto3"

var (
	file_rpc_admin_service_proto_rawDescOnce sync.Once
	file_rpc_admin_service_proto_rawDescData []byte
)

func file_rpc_admin_service_proto_rawDescGZIP() []byte {
	file_rpc_admin_service_proto_rawDescOnce.Do(func() {
		file_rpc_admin_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_admin_service_proto_rawDesc), len(file_rpc_admin_service_proto_rawDesc)))
	})
	return file_rpc_admin_service_proto_rawDescData
}

var file_rpc_admin_service_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_rpc_admin_service_proto_goTypes = []any{
	(*StatusRequest)(nil),        // 0: rpc.StatusRequest
	(*StatusResponse)(nil),       // 1: rpc.StatusResponse
	(*StatsRequest)(nil),         // 2: rpc.StatsRequest
	(*StatsResponse)(nil),        // 3: rpc.StatsResponse
	(*UpdateConfigRequest)(nil),  // 4: rpc.UpdateConfigRequest
	(*UpdateConfigResponse)(nil), // 5: rpc.UpdateConfigResponse
	(*LogsRequest)(nil),          // 6: rpc.LogsRequest
	(*LogsResponse)(nil),         // 7: rpc.LogsResponse
	(*LogEntry)(nil),             // 8: rpc.LogEntry
	(*HealthCheckRequest)(nil),   // 9: rpc.HealthCheckRequest
	(*HealthCheckResponse)(nil),  // 10: rpc.HealthCheckResponse
	(*ConnectionsRequest)(nil),   // 11: rpc.ConnectionsRequest
	(*ConnectionsResponse)(nil),  // 12: rpc.ConnectionsResponse
	(*ConnectionInfo)(nil),       // 13: rpc.ConnectionInfo
	nil,                          // 14: rpc.StatsResponse.ErrorStatsEntry
}
var file_rpc_admin_service_proto_depIdxs = []int32{
	14, // 0: rpc.StatsResponse.error_stats:type_name -> rpc.StatsResponse.ErrorStatsEntry
	8,  // 1: rpc.LogsResponse.entries:type_name -> rpc.LogEntry
	13, // 2: rpc.ConnectionsResponse.connections:type_name -> rpc.ConnectionInfo
	0,  // 3: rpc.AdminService.GetStatus:input_type -> rpc.StatusRequest
	2,  // 4: rpc.AdminService.GetStats:input_type -> rpc.StatsRequest
	4,  // 5: rpc.AdminService.UpdateConfig:input_type -> rpc.UpdateConfigRequest
	6,  // 6: rpc.AdminService.GetLogs:input_type -> rpc.LogsRequest
	9,  // 7: rpc.AdminService.HealthCheck:input_type -> rpc.HealthCheckRequest
	11, // 8: rpc.AdminService.GetConnections:input_type -> rpc.ConnectionsRequest
	1,  // 9: rpc.AdminService.GetStatus:output_type -> rpc.StatusResponse
	3,  // 10: rpc.AdminService.GetStats:output_type -> rpc.StatsResponse
	5,  // 11: rpc.AdminService.UpdateConfig:output_type -> rpc.UpdateConfigResponse
	7,  // 12: rpc.AdminService.GetLogs:output_type -> rpc.LogsResponse
	10, // 13: rpc.AdminService.HealthCheck:output_type -> rpc.HealthCheckResponse
	12, // 14: rpc.AdminService.GetConnections:output_type -> rpc.ConnectionsResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_rpc_admin_service_proto_init() }
func file_rpc_admin_service_proto_init() {
	if File_rpc_admin_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_admin_service_proto_rawDesc), len(file_rpc_admin_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_admin_service_proto_goTypes,
		DependencyIndexes: file_rpc_admin_service_proto_depIdxs,
		MessageInfos:      file_rpc_admin_service_proto_msgTypes,
	}.Build()
	File_rpc_admin_service_proto = out.File
	file_rpc_admin_service_proto_goTypes = nil
	file_rpc_admin_service_proto_depIdxs = nil
}
